Ft create roles permissions
atlp-rwanda/c4-barefoot-frontend pull request #6
Opened 2021-02-22 17:43 UTC by Blaiseniyo

# Description

This set up a project from scratch without using npx create-react-app

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How should this be manually tested or reproduced?

- Clone this repo
- Run the command `npm i`
- Run the command `npm start`

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots (if applicable)

2021-03-03 13:09 UTC, edgar929 submitted a review, later dismissed

2021-03-03 19:56 UTC, CYIMANA-Faisal submitted a review, later dismissed

2021-03-04 07:58 UTC, salviosage requested changes
Please rebase and fix build

2021-03-08 10:14 UTC, salviosage commented
please rebase

2021-03-11 10:22 UTC, merged